schema: v1

repository:
  title: StackSpot HomeAssistant
  description: StackSpot AI Integration with Home Assistant
  license: GPL-3
  type: code
  topics:
    - python
    - ai
    - ai-agent
    - stackspot
    - home-assistant
    - homeassistant-integration
    - hacs-integration
  website:

project:
  status: development
  stack:
    language: python
    framework:
    database:
    protocols:
    tools:
      - home-assistant
      - stackspot