flowchart TD
    user_input[User input] --> history_add_input[Add input to history]
    history_add_input --> history_get[Get full history]
    history_get --> render_prompt[Render integration prompt template]
    render_prompt --> assemble_payload[Assemble payload:<br/>- Integration prompt<br/>- History<br/>- Input]
    assemble_payload --> send_to_stackspot[Send to StackSpot API]
    send_to_stackspot --> apply_stackspot_prompt

    subgraph StackSpot
        apply_stackspot_prompt[Apply StackSpot prompt + payload]
        apply_stackspot_prompt --> call_model[Call StackSpot LLM]
        call_model --> return_response[Return response]
    end

    return_response --> history_add_response[Add response to history]
    return_response --> tokens[Update token count]
    history_add_response --> user_output["Return to user (HA)"]

    style apply_stackspot_prompt fill: #ed4e2b
    style call_model fill: #ed4e2b
    style return_response fill: #ed4e2b