name: '[DEV] Create Develop Release'

on:
  push:
    branches:
      - develop

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create or update tag
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git tag -f develop
          git push origin --force --tags

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: develop
          name: Develop Release
          body: "This is the release release from develop"
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}